### ISSUE TITLE
memory issue

### ISSUE THREAD

**Issue by fatyin88** [jind11/MMM-MCQA#1]
I tried to run bert-race in google colab but it stopped due to memory issue. is it possible to have a set of hyperparameters to run in colab and get a similar result?

**Comment by jind11** [comment]
Which experiment do you want to replicate? And what is your GPU size?

**Comment by fatyin88** [comment]
i want to try bert-race. I am using colab in google and memory size is 12-16 GB.

**Comment by jind11** [comment]
And is it for BERT-Base or BERT-Large? For BERT-Large, 16 GB GPU cannot hold a single batch since each data sample is composed of four choices which comprise of 4 sequences of 512 max_sequence_length. So in order to put a single batch to a 16 GB GPU, you need to decrease the max_sequence_length from 512 to some number smaller, although this will degrade the performance by a little.

**Comment by fatyin88** [comment]
Thanks! let me try it!
